/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jayde.apps.appDisk;

import com.jayde.util.diskutils.DiskToXmlUtil;
import com.jayde.util.diskutils.DiskUtil;
import com.jayde.util.diskutils.PathAndFileCount;

import javax.swing.*;
import java.io.File;
import java.io.IOException;

/**
 * @author Administrator
 */
public class DiskToXmlPanel extends javax.swing.JPanel {

    /**
     * Creates new form DiskToXmlPanel
     */
    public DiskToXmlPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choosePathField = new javax.swing.JTextField("");
        choosePathButton = new javax.swing.JButton();
        choosePathLabel = new javax.swing.JLabel();
        preScanPathLabel = new javax.swing.JLabel();
        preScanPathField = new javax.swing.JTextField();
        preScanButton = new javax.swing.JButton();
        preScanFileLabel = new javax.swing.JLabel();
        preScanFileField = new javax.swing.JTextField();
        preScanResultLabel = new javax.swing.JLabel();
        preScanResultField = new javax.swing.JTextField();
        doScanPathField = new javax.swing.JTextField();
        doScanPathLabel = new javax.swing.JLabel();
        doScanFileField = new javax.swing.JTextField();
        doScanFileLabel = new javax.swing.JLabel();
        doScanResultLabel = new javax.swing.JLabel();
        doScanResultField = new javax.swing.JTextField();
        preScanBar = new javax.swing.JProgressBar();
        doScanBar = new javax.swing.JProgressBar();
        doScanButton = new javax.swing.JButton();
        savePathField = new javax.swing.JTextField();
        savePathButton = new javax.swing.JButton();
        savePathLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1024, 768));
        setLayout(null);

        choosePathField.setEditable(false);
        choosePathField.setText("/Users/mac/IdeaProjects");
        add(choosePathField);
        choosePathField.setBounds(150, 30, 540, 21);

        choosePathButton.setText("jButton1");
        choosePathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePathButtonActionPerformed(evt);
            }
        });
        add(choosePathButton);
        choosePathButton.setBounds(700, 30, 81, 23);

        choosePathLabel.setText("choosePath");
        add(choosePathLabel);
        choosePathLabel.setBounds(30, 30, 110, 15);

        preScanPathLabel.setText("preScanPath");
        add(preScanPathLabel);
        preScanPathLabel.setBounds(30, 160, 110, 15);

        preScanPathField.setEditable(false);
        preScanPathField.setText("jTextField1");
        add(preScanPathField);
        preScanPathField.setBounds(150, 160, 540, 21);

        preScanButton.setText("preScan");
        preScanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preScanButtonActionPerformed(evt);
            }
        });
        add(preScanButton);
        preScanButton.setBounds(20, 130, 81, 23);

        preScanFileLabel.setText("preScanFile");
        add(preScanFileLabel);
        preScanFileLabel.setBounds(30, 200, 110, 15);

        preScanFileField.setEditable(false);
        preScanFileField.setText("jTextField1");
        add(preScanFileField);
        preScanFileField.setBounds(150, 200, 540, 21);

        preScanResultLabel.setText("preScanResult");
        add(preScanResultLabel);
        preScanResultLabel.setBounds(30, 240, 110, 15);

        preScanResultField.setEditable(false);
        preScanResultField.setText("jTextField1");
        add(preScanResultField);
        preScanResultField.setBounds(150, 240, 540, 21);

        doScanPathField.setEditable(false);
        doScanPathField.setText("jTextField1");
        add(doScanPathField);
        doScanPathField.setBounds(160, 520, 540, 21);

        doScanPathLabel.setText("doScanPath");
        add(doScanPathLabel);
        doScanPathLabel.setBounds(40, 520, 110, 15);

        doScanFileField.setEditable(false);
        doScanFileField.setText("jTextField1");
        add(doScanFileField);
        doScanFileField.setBounds(160, 560, 540, 21);

        doScanFileLabel.setText("doScanFile");
        add(doScanFileLabel);
        doScanFileLabel.setBounds(40, 560, 110, 15);

        doScanResultLabel.setText("doScanResult");
        add(doScanResultLabel);
        doScanResultLabel.setBounds(40, 600, 110, 15);

        doScanResultField.setEditable(false);
        doScanResultField.setText("jTextField1");
        add(doScanResultField);
        doScanResultField.setBounds(160, 600, 540, 21);
        add(preScanBar);
        preScanBar.setBounds(150, 140, 540, 14);
        add(doScanBar);
        doScanBar.setBounds(160, 490, 540, 14);

        doScanButton.setText("do");
        doScanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doScanButtonActionPerformed(evt);
            }
        });
        add(doScanButton);
        doScanButton.setBounds(30, 490, 45, 23);

        savePathField.setEditable(false);
        savePathField.setText("jTextField1");
        add(savePathField);
        savePathField.setBounds(150, 450, 540, 21);

        savePathButton.setText("jButton1");
        savePathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePathButtonActionPerformed(evt);
            }
        });
        add(savePathButton);
        savePathButton.setBounds(700, 450, 81, 23);

        savePathLabel.setText("savePath");
        add(savePathLabel);
        savePathLabel.setBounds(30, 450, 110, 15);
    }// </editor-fold>//GEN-END:initComponents

    private void choosePathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePathButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.showDialog(new JLabel(), "选择");
        File file = chooser.getSelectedFile();
        if (file != null)
            choosePathField.setText(file.getAbsoluteFile().toString());

    }//GEN-LAST:event_choosePathButtonActionPerformed

    private void preScanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preScanButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("preScan");

        PathAndFileCount pathAndFileCount = DiskToXmlUtil.prePathCount(choosePathField.getText());
        preScanPathField.setText(pathAndFileCount.getAllPathCount() + "");
        preScanFileField.setText(pathAndFileCount.getAllFileCount() + "");
    }//GEN-LAST:event_preScanButtonActionPerformed

    private void savePathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePathButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("savePath");
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.showDialog(new JLabel(), "选择");
        File file = chooser.getSelectedFile();
        if (file != null) {
            String scanpathname = choosePathField.getText();
            File scanpath = new File(scanpathname);
            if (scanpath != null) {
                String name = file.getAbsoluteFile().toString() + "/" + scanpath.getName() + ".xml";
                savePathField.setText(name);
            }
        }
    }//GEN-LAST:event_savePathButtonActionPerformed

    long currentPathCount = 0;
    long currentFileCount = 0;
    long pathAllCount = 0;
    long fileAllCount = 0;

    private void doScanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doScanButtonActionPerformed
        // TODO add your handling code here:
        currentPathCount = 0;
        currentFileCount = 0;
        doScanBar.setValue(0);
        System.out.println("doScan");
        pathAllCount = Long.parseLong(preScanPathField.getText().trim());
        fileAllCount = Long.parseLong(preScanFileField.getText().trim());
        File dir = new File(choosePathField.getText());
        PathAndFileCount pathAndFileCount = new PathAndFileCount();
        pathAndFileCount.setAllPathCount(Long.parseLong(preScanPathField.getText()));
        pathAndFileCount.setAllFileCount(Long.parseLong(preScanFileField.getText()));

        try {
            DiskToXmlUtil.fromDiskToXml(dir.getName(), choosePathField.getText(), savePathField.getText(),pathAndFileCount);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_doScanButtonActionPerformed

    private void cyclePath(File path) {
        currentPathCount++;
        long barpos = currentPathCount * 100 / pathAllCount;
        System.out.println("c:" + currentPathCount + "    a:" + pathAllCount + "    b:" + barpos);
        doScanBar.setValue((int) barpos);
        File[] files = path.listFiles();
        if (files != null) {
            for (File file : files) {
                if (file.isDirectory()) {
                    cyclePath(file);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton choosePathButton;
    private javax.swing.JTextField choosePathField;
    private javax.swing.JLabel choosePathLabel;
    private javax.swing.JProgressBar doScanBar;
    private javax.swing.JButton doScanButton;
    private javax.swing.JTextField doScanFileField;
    private javax.swing.JLabel doScanFileLabel;
    private javax.swing.JTextField doScanPathField;
    private javax.swing.JLabel doScanPathLabel;
    private javax.swing.JTextField doScanResultField;
    private javax.swing.JLabel doScanResultLabel;
    private javax.swing.JProgressBar preScanBar;
    private javax.swing.JButton preScanButton;
    private javax.swing.JTextField preScanFileField;
    private javax.swing.JLabel preScanFileLabel;
    private javax.swing.JTextField preScanPathField;
    private javax.swing.JLabel preScanPathLabel;
    private javax.swing.JTextField preScanResultField;
    private javax.swing.JLabel preScanResultLabel;
    private javax.swing.JButton savePathButton;
    private javax.swing.JTextField savePathField;
    private javax.swing.JLabel savePathLabel;
    // End of variables declaration//GEN-END:variables

}
